server:
  port: 8761

spring:
  application:
    name: geektoys-discovery-service

eureka:
  instance:
    hostname: discovery-service
  client:
    register-with-eureka: false
    fetch-registry: false
