FROM openjdk:21
WORKDIR /app
# Nombre del jar generado en el target de discovery-service
COPY target/geektoys-pedido-service-0.0.1-SNAPSHOT.jar pedido-service.jar
EXPOSE 8762
ENTRYPOINT ["java", "-jar", "pedido-service.jar"] 
