server:
  port: 8081

spring:
  application:
    name: pedido-service

  datasource:
    # Datos los trae Spring Cloud Config, desde el docker-compose.yml
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      # Los servicios se comunican entre si internamente por docker compose. Aca tiene el nombre de el contenedor. y no localhost.
      defaultZone: http://discovery-service:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    # Nombre con el que se registra en Eureka
    hostname: pedido-service

kafka:
  consumer:
    bootstrap-servers: kafka:9092
    group-id: pedido-group
    enable-auto-commit: true
    auto-offset-reset: earliest
  producer:
    bootstrap-servers: kafka:9092
